name: URLhaus Data Fetcher

on:
  schedule:
    - cron: '19 * * * *'
  workflow_dispatch:

# TOTO TU CHÝBALO: Povolí workeru zapisovať zmeny do kódu
permissions:
  contents: write

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python urlhaus.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add urlhaus_urls.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizácia urlhaus_urls.txt" && git push)
